/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.Questionario_DAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Questionario;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Milton
 */
public class Frm_Questionario_Lista extends javax.swing.JDialog {

	/**
	 * Creates new form Frm_Questionario_Lista2
	 */
	public int questionario_id = 0;
	public String descricao = "";
	private int tipo_tela;
		
	public Frm_Questionario_Lista(java.awt.Frame parent, boolean modal, int p_tipo_tela ) {
		super(parent, modal);
		initComponents();
		this.tipo_tela = p_tipo_tela;
		listar();
		this.tipo_tela = p_tipo_tela;
		this.jButton_Confirma.setVisible(false);
		this.jButton_Grafico.setVisible(false);
		if (this.tipo_tela == 1 ){
		   this.setModalityType(DEFAULT_MODALITY_TYPE.APPLICATION_MODAL);
		}
		if (this.tipo_tela == 2) {
		   this.jButton_Confirma.setVisible(true);
		}
		if (this.tipo_tela == 3) {
		   this.jButton_Grafico.setVisible(true);
		}

		
		setSize(950,500);	
		
	}


	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Questionario = new javax.swing.JPanel();
        jScrollPane_questionario = new javax.swing.JScrollPane();
        jTable_Questionario = new javax.swing.JTable();
        jPanel_botoes = new javax.swing.JPanel();
        jButton_Grafico = new javax.swing.JButton();
        jButton_Confirma = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avaliador - Seleciona Questionário");
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setLocationByPlatform(true);
        setModalityType(null);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 500));

        jPanel_Questionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane_questionario.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane_questionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane_questionario.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane_questionario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N

        jTable_Questionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ));
        jTable_Questionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QuestionarioMouseClicked(evt);
            }
        });
        jScrollPane_questionario.setViewportView(jTable_Questionario);

        javax.swing.GroupLayout jPanel_QuestionarioLayout = new javax.swing.GroupLayout(jPanel_Questionario);
        jPanel_Questionario.setLayout(jPanel_QuestionarioLayout);
        jPanel_QuestionarioLayout.setHorizontalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_questionario, javax.swing.GroupLayout.DEFAULT_SIZE, 922, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel_QuestionarioLayout.setVerticalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_questionario, javax.swing.GroupLayout.DEFAULT_SIZE, 297, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel_botoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grafico_32x32.jpeg"))); // NOI18N
        jButton_Grafico.setText("Gráfico");
        jButton_Grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficoActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Grafico);

        jButton_Confirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok_32x32.jpg"))); // NOI18N
        jButton_Confirma.setText("Confirma");
        jButton_Confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmaActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Confirma);

        jButton_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Recycle_40148.png"))); // NOI18N
        jButton_Listar.setText("Listar");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Listar);

        jButton_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.jpg"))); // NOI18N
        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Sair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Questionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Questionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
	private void listar() {
				DefaultTableModel model = new DefaultTableModel();
				String headers[] = {"Código", "Descrição"};
				model.setColumnIdentifiers(headers);
				Questionario questionario = new Questionario();
				for (Questionario q : Questionario_DAO.listar()) {
					model.addRow(new Object[]{String.valueOf(q.getQuestionario_id()), String.valueOf(q.getDescricao())});
				}
				this.jTable_Questionario.setModel(model);
				jTable_Questionario.getColumnModel().getColumn(0).setMaxWidth(100);
				jTable_Questionario.getColumnModel().getColumn(1).setMaxWidth(1200);
				jTable_Questionario.setDefaultEditor(Object.class, null);

	}
        private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarActionPerformed
                // TODO add your handling code here:
                listar();
        }//GEN-LAST:event_jButton_ListarActionPerformed

        private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
                this.dispose();
        }//GEN-LAST:event_jButton_SairActionPerformed

	private void get_questionario_info(){
                int row = jTable_Questionario.getSelectedRow();
                int col = jTable_Questionario.getSelectedColumn();	
                
		Object data_id = (Object)jTable_Questionario.getValueAt(row, 0);
                
                if (data_id != null){
		   this.questionario_id =  Integer.parseInt(String.valueOf(data_id));
                }
		System.out.println("questionario_id: " + this.questionario_id);
		Object data_descricao = (Object)jTable_Questionario.getValueAt(row, 1);
                if (data_descricao != null){
		   this.descricao =  String.valueOf(data_descricao);
                }				
	}
        private void jTable_QuestionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QuestionarioMouseClicked

		get_questionario_info();
		System.out.println("tipo_tela: " + this.tipo_tela);
		if ( this.tipo_tela == 1 ) {		   
		     this.setVisible(false);
		}
        }//GEN-LAST:event_jTable_QuestionarioMouseClicked

        private void jButton_ConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmaActionPerformed
                // TODO add your handling code here:
	
        }//GEN-LAST:event_jButton_ConfirmaActionPerformed

        private void jButton_GraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficoActionPerformed
		if (this.questionario_id <= 0) {
			JOptionPane.showMessageDialog(this, "Selecione um questionário para geração do gráfico.");
			this.jTable_Questionario.requestFocus();
			
		} else {
			Frm_Questionario_Grafico chart = new Frm_Questionario_Grafico("Estatistica", "Questionário: " + this.descricao, this.questionario_id);
			chart.questionario_id = this.questionario_id;
			chart.pack();
			RefineryUtilities.centerFrameOnScreen(chart);
			chart.setVisible(true);
		}
        }//GEN-LAST:event_jButton_GraficoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_Questionario_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_Questionario_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_Questionario_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_Questionario_Lista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Frm_Questionario_Lista dialog = new Frm_Questionario_Lista(new javax.swing.JFrame(), true,3);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Confirma;
    private javax.swing.JButton jButton_Grafico;
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JPanel jPanel_Questionario;
    private javax.swing.JPanel jPanel_botoes;
    private javax.swing.JScrollPane jScrollPane_questionario;
    private javax.swing.JTable jTable_Questionario;
    // End of variables declaration//GEN-END:variables
}
