/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

/**
 *
 * @author Milton
 */
public class Frm_Selecao extends javax.swing.JFrame {

	/**
	 * Creates new form Frm_Selecao
	 */
	public Frm_Selecao() {
		initComponents();
	
	}	
	
	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Botoes = new javax.swing.JPanel();
        jButton_Questionario = new javax.swing.JButton();
        jButton_Resposta = new javax.swing.JButton();
        jButton_Relatorio_Cadastro = new javax.swing.JButton();
        jButton_Grafico = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();
        jButton_Tabela_Frequencia = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setResizable(false);

        jPanel_Botoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel_Botoes.setPreferredSize(new java.awt.Dimension(950, 420));

        jButton_Questionario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Monitor_40139.png"))); // NOI18N
        jButton_Questionario.setText("Questionário");
        jButton_Questionario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_QuestionarioActionPerformed(evt);
            }
        });

        jButton_Resposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Help_40132.png"))); // NOI18N
        jButton_Resposta.setText("Resposta");
        jButton_Resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_RespostaActionPerformed(evt);
            }
        });

        jButton_Relatorio_Cadastro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Search2_40156.png"))); // NOI18N
        jButton_Relatorio_Cadastro.setText("Consulta");
        jButton_Relatorio_Cadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Relatorio_CadastroActionPerformed(evt);
            }
        });

        jButton_Grafico.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/grafico_32x32.jpeg"))); // NOI18N
        jButton_Grafico.setText("Gráfico");
        jButton_Grafico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_GraficoActionPerformed(evt);
            }
        });

        jButton_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.jpg"))); // NOI18N
        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });

        jButton_Tabela_Frequencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Graph_40129.png"))); // NOI18N
        jButton_Tabela_Frequencia.setText("Tabela de Frequencia");
        jButton_Tabela_Frequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tabela_FrequenciaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_BotoesLayout = new javax.swing.GroupLayout(jPanel_Botoes);
        jPanel_Botoes.setLayout(jPanel_BotoesLayout);
        jPanel_BotoesLayout.setHorizontalGroup(
            jPanel_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_Questionario, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, 902, Short.MAX_VALUE)
                    .addComponent(jButton_Resposta, javax.swing.GroupLayout.Alignment.CENTER, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Relatorio_Cadastro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Grafico, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton_Tabela_Frequencia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel_BotoesLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jButton_Sair, javax.swing.GroupLayout.DEFAULT_SIZE, 402, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        jPanel_BotoesLayout.setVerticalGroup(
            jPanel_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_BotoesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Questionario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Resposta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Relatorio_Cadastro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Grafico)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_Tabela_Frequencia)
                .addContainerGap(254, Short.MAX_VALUE))
            .addGroup(jPanel_BotoesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_BotoesLayout.createSequentialGroup()
                    .addContainerGap(294, Short.MAX_VALUE)
                    .addComponent(jButton_Sair)
                    .addContainerGap()))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Botoes, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Botoes, javax.swing.GroupLayout.DEFAULT_SIZE, 498, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
        
        private void jButton_QuestionarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_QuestionarioActionPerformed
		Frm_Questionario f = new Frm_Questionario();
		f.setVisible(true);
		f.setLocationRelativeTo(null);  		
        }//GEN-LAST:event_jButton_QuestionarioActionPerformed

        private void jButton_RespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_RespostaActionPerformed
                // TODO add your handling code here:

		Frm_Resposta f = new Frm_Resposta();
		f.setVisible(true);
		f.setLocationRelativeTo(null);  		
        }//GEN-LAST:event_jButton_RespostaActionPerformed

        private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
                // TODO add your handling code here:
		        this.dispose();		
        }//GEN-LAST:event_jButton_SairActionPerformed

        private void jButton_GraficoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_GraficoActionPerformed
                // TODO add your handling code here:
		Frm_Questionario_Lista frm_questionario_lista = new Frm_Questionario_Lista(this, true,3);
		frm_questionario_lista.setVisible(true);
		if (frm_questionario_lista.questionario_id > 0) {
			//this.jTextField_questionario_id.setText(frm_questionario_lista.id_questionario + "");
			//jButton_ConsultarActionPerformed(null);
		}		

	
        }//GEN-LAST:event_jButton_GraficoActionPerformed

        private void jButton_Relatorio_CadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Relatorio_CadastroActionPerformed
                // TODO add your handling code here:
		Frm_Resposta_Lista f = new Frm_Resposta_Lista();
		f.setVisible(true);
        }//GEN-LAST:event_jButton_Relatorio_CadastroActionPerformed

    private void jButton_Tabela_FrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tabela_FrequenciaActionPerformed
        // TODO add your handling code here:
        Frm_Tabela_Frequencia f = new Frm_Tabela_Frequencia(this, true,3);
        f.setVisible(true);
    }//GEN-LAST:event_jButton_Tabela_FrequenciaActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_Selecao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Frm_Selecao f = new Frm_Selecao();
				f.setVisible(true);
				f.setLocationRelativeTo(null);  				
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Grafico;
    private javax.swing.JButton jButton_Questionario;
    private javax.swing.JButton jButton_Relatorio_Cadastro;
    private javax.swing.JButton jButton_Resposta;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JButton jButton_Tabela_Frequencia;
    private javax.swing.JPanel jPanel_Botoes;
    // End of variables declaration//GEN-END:variables
}
