/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.Questionario_DAO;
import dao.Questionario_Item_DAO;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Questionario;
import modelo.Questionario_Item;
import org.jfree.ui.RefineryUtilities;

/**
 *
 * @author Milton
 */
public class Frm_Tabela_Frequencia extends javax.swing.JDialog {

	/**
	 * Creates new form Frm_Questionario_Lista2
	 */
	public int questionario_id = 0;
        public int questionario_item_id = 0;
	public String descricao = "";
	private int tipo_tela;
		
	public Frm_Tabela_Frequencia(java.awt.Frame parent, boolean modal, int p_tipo_tela ) {
		super(parent, modal);
		initComponents();
		this.tipo_tela = p_tipo_tela;
		listar();
		this.tipo_tela = p_tipo_tela;
		if (this.tipo_tela == 1 ){
		   //this.setModalExclusionType(ModalExclusionType.TOOLKIT_EXCLUDE);
		   this.setModalityType(DEFAULT_MODALITY_TYPE.APPLICATION_MODAL);
		}
		
		setSize(950,500);	
		
	}


	

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel_Questionario = new javax.swing.JPanel();
        jScrollPane_questionario = new javax.swing.JScrollPane();
        jTable_Questionario = new javax.swing.JTable();
        jScrollPane_Questionario_Item = new javax.swing.JScrollPane();
        jTable_Questionario_Item = new javax.swing.JTable();
        jPanel_botoes = new javax.swing.JPanel();
        jButton_Tabela_Frequencia = new javax.swing.JButton();
        jButton_Listar = new javax.swing.JButton();
        jButton_Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avaliador - Tabela de Frequencia");
        setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        setLocationByPlatform(true);
        setModalityType(null);
        setResizable(false);
        setSize(new java.awt.Dimension(950, 500));

        jPanel_Questionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jScrollPane_questionario.setBackground(new java.awt.Color(255, 255, 204));
        jScrollPane_questionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane_questionario.setViewportBorder(javax.swing.BorderFactory.createEtchedBorder());
        jScrollPane_questionario.setFont(new java.awt.Font("Dialog", 0, 24)); // NOI18N
        jScrollPane_questionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane_questionarioMouseClicked(evt);
            }
        });

        jTable_Questionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Código", "Descrição"
            }
        ));
        jTable_Questionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_QuestionarioMouseClicked(evt);
            }
        });
        jScrollPane_questionario.setViewportView(jTable_Questionario);

        jScrollPane_Questionario_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jScrollPane_Questionario_ItemMouseClicked(evt);
            }
        });

        jTable_Questionario_Item.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null}
            },
            new String [] {
                "Questionário", "Pergunta", "Descrição"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable_Questionario_Item.setColumnSelectionAllowed(true);
        jTable_Questionario_Item.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable_Questionario_ItemMouseClicked(evt);
            }
        });
        jScrollPane_Questionario_Item.setViewportView(jTable_Questionario_Item);
        jTable_Questionario_Item.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable_Questionario_Item.getColumnModel().getColumnCount() > 0) {
            jTable_Questionario_Item.getColumnModel().getColumn(0).setResizable(false);
            jTable_Questionario_Item.getColumnModel().getColumn(0).setPreferredWidth(20);
            jTable_Questionario_Item.getColumnModel().getColumn(1).setResizable(false);
            jTable_Questionario_Item.getColumnModel().getColumn(1).setPreferredWidth(20);
            jTable_Questionario_Item.getColumnModel().getColumn(2).setResizable(false);
            jTable_Questionario_Item.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        javax.swing.GroupLayout jPanel_QuestionarioLayout = new javax.swing.GroupLayout(jPanel_Questionario);
        jPanel_Questionario.setLayout(jPanel_QuestionarioLayout);
        jPanel_QuestionarioLayout.setHorizontalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane_questionario, javax.swing.GroupLayout.DEFAULT_SIZE, 926, Short.MAX_VALUE)
                    .addComponent(jScrollPane_Questionario_Item))
                .addContainerGap())
        );
        jPanel_QuestionarioLayout.setVerticalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane_questionario, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane_Questionario_Item, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        jPanel_botoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Tabela_Frequencia.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Graph_40129.png"))); // NOI18N
        jButton_Tabela_Frequencia.setText("Tabela de Frequencia");
        jButton_Tabela_Frequencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Tabela_FrequenciaActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Tabela_Frequencia);

        jButton_Listar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Recycle_40148.png"))); // NOI18N
        jButton_Listar.setText("Listar");
        jButton_Listar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ListarActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Listar);

        jButton_Sair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.jpg"))); // NOI18N
        jButton_Sair.setText("Sair");
        jButton_Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SairActionPerformed(evt);
            }
        });
        jPanel_botoes.add(jButton_Sair);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Questionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel_Questionario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel_botoes, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
	private void listar() {
				DefaultTableModel model = new DefaultTableModel();
				String headers[] = {"Código", "Descrição"};
				model.setColumnIdentifiers(headers);
				Questionario questionario = new Questionario();
				for (Questionario q : Questionario_DAO.listar()) {
					model.addRow(new Object[]{String.valueOf(q.getQuestionario_id()), String.valueOf(q.getDescricao())});
				}
				this.jTable_Questionario.setModel(model);
				jTable_Questionario.getColumnModel().getColumn(0).setMaxWidth(100);
				jTable_Questionario.getColumnModel().getColumn(1).setMaxWidth(1200);
				jTable_Questionario.setDefaultEditor(Object.class, null);

	}
        
        
        private void listar_Item_Questionario() {
            if (this.questionario_id > 0 ) {
                DefaultTableModel model = new DefaultTableModel();
                String headers[] = {"Questionario", "Pergunta","Ordem", "Descrição"};
                model.setColumnIdentifiers(headers);
                Questionario_Item questionario_item = new Questionario_Item();
                for (Questionario_Item q : Questionario_Item_DAO.listar_Questionario_Resposta(this.questionario_id)) {
                        model.addRow(new Object[]{String.valueOf(q.getQuestionario_id()), String.valueOf(q.getQuestionario_item_id()), String.valueOf(q.getOrdem()), String.valueOf(q.getDescricao())});;;;;
                }
                this.jTable_Questionario_Item.setModel(model);
                jTable_Questionario_Item.getColumnModel().getColumn(0).setMaxWidth(0);
                jTable_Questionario_Item.getColumnModel().getColumn(1).setMaxWidth(0);
                jTable_Questionario_Item.getColumnModel().getColumn(2).setMaxWidth(1200);
                jTable_Questionario_Item.setDefaultEditor(Object.class, null);
        }

	}
        private void jButton_ListarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ListarActionPerformed
                // TODO add your handling code here:
                listar();
        }//GEN-LAST:event_jButton_ListarActionPerformed

        private void jButton_SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SairActionPerformed
                this.dispose();
        }//GEN-LAST:event_jButton_SairActionPerformed

	private void get_questionario_info(){
                int row = jTable_Questionario.getSelectedRow();
                int col = jTable_Questionario.getSelectedColumn();	
                
		Object data_id = (Object)jTable_Questionario.getValueAt(row, 0);                
                
                if (data_id != null){
		   this.questionario_id =  Integer.parseInt(String.valueOf(data_id));
                }
		System.out.println("questionario_id: " + this.questionario_id);

	}
        
	private void get_questionario_item_info(){
            try{
                int row = jTable_Questionario_Item.getSelectedRow();
                int col = jTable_Questionario_Item.getSelectedColumn();	
                
		Object data_id = (Object)jTable_Questionario_Item.getValueAt(row, 0);
                Object data_item_id = (Object)jTable_Questionario_Item.getValueAt(row, 1);
                
                if (data_id != null){
		   this.questionario_id =  Integer.parseInt(String.valueOf(data_id));
                }
                if (data_item_id != null){
		   this.questionario_item_id =  Integer.parseInt(String.valueOf(data_item_id));
                }
                
		System.out.println("questionario_id: " + this.questionario_id);
                System.out.println("questionario_item_)id: " + this.questionario_item_id);
            } catch (Exception e){
                System.out.println(e);
            }
	}
        
        
        private void jTable_QuestionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_QuestionarioMouseClicked

		get_questionario_info();
		System.out.println("tipo_tela: " + this.tipo_tela);
		if ( this.tipo_tela == 1 ) {		   
		     this.setVisible(false);
		}
                listar_Item_Questionario();
        }//GEN-LAST:event_jTable_QuestionarioMouseClicked

        private void jButton_Tabela_FrequenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Tabela_FrequenciaActionPerformed
                // TODO add your handling code here:
                get_questionario_item_info();
                if (this.questionario_item_id <= 0){
                    JOptionPane.showMessageDialog(this, "Selecione uma pergunta questionário para geração do gráfico.");
		    //this.jTable_Questionario.requestFocus();                    
                } else {
                    Frm_Tabela_Frequencia_Detalhe frm_tabela_frequencia_detalhe = new Frm_Tabela_Frequencia_Detalhe(this.questionario_item_id);
                    frm_tabela_frequencia_detalhe.questionario_item_id = this.questionario_item_id;
                    frm_tabela_frequencia_detalhe.setVisible(true);
                }
                           
	
        }//GEN-LAST:event_jButton_Tabela_FrequenciaActionPerformed

    private void jTable_Questionario_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable_Questionario_ItemMouseClicked
        // TODO add your handling code here
        get_questionario_item_info();

    }//GEN-LAST:event_jTable_Questionario_ItemMouseClicked

    private void jScrollPane_questionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane_questionarioMouseClicked
        // TODO add your handling code here
        
    }//GEN-LAST:event_jScrollPane_questionarioMouseClicked

    private void jScrollPane_Questionario_ItemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jScrollPane_Questionario_ItemMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jScrollPane_Questionario_ItemMouseClicked

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_Tabela_Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_Tabela_Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_Tabela_Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_Tabela_Frequencia.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>
		//</editor-fold>

		/* Create and display the dialog */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				Frm_Tabela_Frequencia dialog = new Frm_Tabela_Frequencia(new javax.swing.JFrame(), true,3);
				dialog.addWindowListener(new java.awt.event.WindowAdapter() {
					@Override
					public void windowClosing(java.awt.event.WindowEvent e) {
						System.exit(0);
					}
				});
				dialog.setVisible(true);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Listar;
    private javax.swing.JButton jButton_Sair;
    private javax.swing.JButton jButton_Tabela_Frequencia;
    private javax.swing.JPanel jPanel_Questionario;
    private javax.swing.JPanel jPanel_botoes;
    private javax.swing.JScrollPane jScrollPane_Questionario_Item;
    private javax.swing.JScrollPane jScrollPane_questionario;
    private javax.swing.JTable jTable_Questionario;
    private javax.swing.JTable jTable_Questionario_Item;
    // End of variables declaration//GEN-END:variables
}
