/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package forms;

import dao.Questionario_DAO;
import javax.swing.JOptionPane;
import modelo.Questionario_Resposta;
import dao.Questionario_Reposta_DAO;
import java.io.File;
import javax.swing.JFileChooser;
import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import modelo.Questionario;
import modelo.Questionario_Item;
import modelo.Questionario_Resposta_Item;

/**
 *
 * @author Milton
 */
public class Frm_Resposta extends javax.swing.JFrame {

	/**
	 * Creates new form Frm_Resposta
	 */
	final JFileChooser fc = new JFileChooser();

	public int id_questionario;
	private int indice;
	private int min = -1;
	private int max = -1;

	ArrayList<Questionario_Resposta_Item> lista_Resposta_Item = new ArrayList();

	public Frm_Resposta() {
		initComponents();
		setSize(950,500);	
		limpar(2);
	}

	/**
	 * This method is called from within the constructor to initialize the
	 * form. WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane_Resposta = new javax.swing.JTabbedPane();
        jPanel_Questionario = new javax.swing.JPanel();
        jLabel_questionario_id = new javax.swing.JLabel();
        jTextField_questionario_id = new javax.swing.JTextField();
        jLabel_descricao = new javax.swing.JLabel();
        jTextField_descricao = new javax.swing.JTextField();
        jButton_Consultar = new javax.swing.JButton();
        jLabel_nome = new javax.swing.JLabel();
        jTextField_nome = new javax.swing.JTextField();
        jLabel_email = new javax.swing.JLabel();
        jTextField_email = new javax.swing.JTextField();
        jLabel_score = new javax.swing.JLabel();
        jFormattedTextField_Score = new javax.swing.JFormattedTextField();
        jLabel_tempo = new javax.swing.JLabel();
        jFormattedTextField_Tempo = new javax.swing.JFormattedTextField();
        jButton_score = new javax.swing.JButton();
        jPanel_Botoes2 = new javax.swing.JPanel();
        jButton_Confirma = new javax.swing.JButton();
        jButton_Cancelar1 = new javax.swing.JButton();
        jButton_Sair1 = new javax.swing.JButton();
        jPanel_Respotas = new javax.swing.JPanel();
        jPanel_Botoes1 = new javax.swing.JPanel();
        jButton_Anterior = new javax.swing.JButton();
        jButton_Proximo = new javax.swing.JButton();
        jLabel_indice_pergunta = new javax.swing.JLabel();
        jLabel_indice_posicao = new javax.swing.JLabel();
        pn_estrela1 = new componente.pn_estrela();
        jPanel_Botoes3 = new javax.swing.JPanel();
        jButton_Confirma_Resposta = new javax.swing.JButton();
        jButton_Cancelar_Resposta = new javax.swing.JButton();
        jButton_Sair_Resposta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Avaliador - Resposta do Questionário");
        setLocationByPlatform(true);
        setPreferredSize(new java.awt.Dimension(950, 500));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane_Resposta.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jTabbedPane_Resposta.setFont(jTabbedPane_Resposta.getFont().deriveFont(jTabbedPane_Resposta.getFont().getStyle() & ~java.awt.Font.BOLD, jTabbedPane_Resposta.getFont().getSize()+6));

        jPanel_Questionario.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel_questionario_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_questionario_id.setForeground(new java.awt.Color(255, 0, 0));
        jLabel_questionario_id.setLabelFor(jTextField_questionario_id);
        jLabel_questionario_id.setText("Questionário:");

        jTextField_questionario_id.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_questionario_id.setEnabled(false);
        jTextField_questionario_id.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_questionario_idActionPerformed(evt);
            }
        });

        jLabel_descricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel_descricao.setForeground(new java.awt.Color(0, 0, 51));
        jLabel_descricao.setLabelFor(jTextField_descricao);
        jLabel_descricao.setText("Descrição:");
        jLabel_descricao.setEnabled(false);

        jTextField_descricao.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jTextField_descricao.setEnabled(false);
        jTextField_descricao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField_descricaoActionPerformed(evt);
            }
        });

        jButton_Consultar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Consultar.png"))); // NOI18N
        jButton_Consultar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConsultarActionPerformed(evt);
            }
        });

        jLabel_nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_nome.setText("Nome:");

        jTextField_nome.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel_email.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_email.setText("E-Mail:");

        jTextField_email.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N

        jLabel_score.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_score.setText("Score:");

        jFormattedTextField_Score.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_Score.setEnabled(false);
        jFormattedTextField_Score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_ScoreActionPerformed(evt);
            }
        });

        jLabel_tempo.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel_tempo.setText("Tempo:");

        jFormattedTextField_Tempo.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter()));
        jFormattedTextField_Tempo.setEnabled(false);
        jFormattedTextField_Tempo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_TempoActionPerformed(evt);
            }
        });

        jButton_score.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Game_40128.png"))); // NOI18N
        jButton_score.setText("Score");
        jButton_score.setEnabled(false);
        jButton_score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_scoreActionPerformed(evt);
            }
        });

        jPanel_Botoes2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Confirma.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok_32x32.jpg"))); // NOI18N
        jButton_Confirma.setText("Confirma");
        jButton_Confirma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ConfirmaActionPerformed(evt);
            }
        });
        jPanel_Botoes2.add(jButton_Confirma);

        jButton_Cancelar1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar.png"))); // NOI18N
        jButton_Cancelar1.setText("Cancelar");
        jButton_Cancelar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancelar1ActionPerformed(evt);
            }
        });
        jPanel_Botoes2.add(jButton_Cancelar1);

        jButton_Sair1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.jpg"))); // NOI18N
        jButton_Sair1.setText("Sair");
        jButton_Sair1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair1ActionPerformed(evt);
            }
        });
        jPanel_Botoes2.add(jButton_Sair1);

        javax.swing.GroupLayout jPanel_QuestionarioLayout = new javax.swing.GroupLayout(jPanel_Questionario);
        jPanel_Questionario.setLayout(jPanel_QuestionarioLayout);
        jPanel_QuestionarioLayout.setHorizontalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                        .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_descricao)
                                    .addComponent(jLabel_questionario_id))
                                .addGap(20, 20, 20)
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                                        .addComponent(jTextField_questionario_id, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(jTextField_descricao)))
                            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_nome)
                                    .addComponent(jLabel_email))
                                .addGap(71, 71, 71)
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_nome)
                                    .addComponent(jTextField_email))))
                        .addGap(18, 18, 18))
                    .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                        .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel_score)
                                    .addComponent(jLabel_tempo))
                                .addGap(64, 64, 64)
                                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFormattedTextField_Tempo, javax.swing.GroupLayout.DEFAULT_SIZE, 88, Short.MAX_VALUE)
                                    .addComponent(jFormattedTextField_Score))
                                .addGap(18, 18, 18)
                                .addComponent(jButton_score, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel_Botoes2, javax.swing.GroupLayout.PREFERRED_SIZE, 393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(532, Short.MAX_VALUE))))
        );
        jPanel_QuestionarioLayout.setVerticalGroup(
            jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_QuestionarioLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_questionario_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel_questionario_id))
                    .addComponent(jButton_Consultar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_descricao)
                    .addComponent(jTextField_descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel_nome))
                .addGap(18, 18, 18)
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel_email)
                    .addComponent(jTextField_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_score, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_QuestionarioLayout.createSequentialGroup()
                        .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_score)
                            .addComponent(jFormattedTextField_Score, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_QuestionarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel_tempo)
                            .addComponent(jFormattedTextField_Tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(26, 26, 26)
                .addComponent(jPanel_Botoes2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        jTabbedPane_Resposta.addTab("Questionário", jPanel_Questionario);

        jPanel_Respotas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel_Botoes1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Anterior.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Left arrow_40136(1).png"))); // NOI18N
        jButton_Anterior.setText("Anterior");
        jButton_Anterior.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_AnteriorActionPerformed(evt);
            }
        });

        jButton_Proximo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/iconfinder_Right arrow_40151.png"))); // NOI18N
        jButton_Proximo.setText("Proxima");
        jButton_Proximo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProximoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_Botoes1Layout = new javax.swing.GroupLayout(jPanel_Botoes1);
        jPanel_Botoes1.setLayout(jPanel_Botoes1Layout);
        jPanel_Botoes1Layout.setHorizontalGroup(
            jPanel_Botoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_Botoes1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton_Anterior)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton_Proximo)
                .addContainerGap())
        );
        jPanel_Botoes1Layout.setVerticalGroup(
            jPanel_Botoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_Botoes1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel_Botoes1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Proximo, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_Anterior, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jLabel_indice_pergunta.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_indice_pergunta.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_indice_pergunta.setText("O QUE ACHOU DA JOGABILIDADE?");
        jLabel_indice_pergunta.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jLabel_indice_posicao.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel_indice_posicao.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel_indice_posicao.setText("Pergunta 01 de 10.");
        jLabel_indice_posicao.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        pn_estrela1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        pn_estrela1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pn_estrela1MouseClicked(evt);
            }
        });
        pn_estrela1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                pn_estrela1PropertyChange(evt);
            }
        });

        jPanel_Botoes3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton_Confirma_Resposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/ok_32x32.jpg"))); // NOI18N
        jButton_Confirma_Resposta.setText("Confirma");
        jButton_Confirma_Resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Confirma_RespostaActionPerformed(evt);
            }
        });
        jPanel_Botoes3.add(jButton_Confirma_Resposta);

        jButton_Cancelar_Resposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Cancelar.png"))); // NOI18N
        jButton_Cancelar_Resposta.setText("Cancelar");
        jButton_Cancelar_Resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Cancelar_RespostaActionPerformed(evt);
            }
        });
        jPanel_Botoes3.add(jButton_Cancelar_Resposta);

        jButton_Sair_Resposta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icones/Sair.jpg"))); // NOI18N
        jButton_Sair_Resposta.setText("Sair");
        jButton_Sair_Resposta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_Sair_RespostaActionPerformed(evt);
            }
        });
        jPanel_Botoes3.add(jButton_Sair_Resposta);

        javax.swing.GroupLayout jPanel_RespotasLayout = new javax.swing.GroupLayout(jPanel_Respotas);
        jPanel_Respotas.setLayout(jPanel_RespotasLayout);
        jPanel_RespotasLayout.setHorizontalGroup(
            jPanel_RespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RespotasLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel_RespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RespotasLayout.createSequentialGroup()
                        .addGroup(jPanel_RespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(pn_estrela1, javax.swing.GroupLayout.DEFAULT_SIZE, 543, Short.MAX_VALUE)
                            .addComponent(jPanel_Botoes3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel_Botoes1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(179, 179, 179))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RespotasLayout.createSequentialGroup()
                        .addGroup(jPanel_RespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel_indice_pergunta, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
                            .addComponent(jLabel_indice_posicao, javax.swing.GroupLayout.PREFERRED_SIZE, 867, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(34, 34, 34))))
        );
        jPanel_RespotasLayout.setVerticalGroup(
            jPanel_RespotasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_RespotasLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jLabel_indice_posicao, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel_indice_pergunta)
                .addGap(18, 18, 18)
                .addComponent(pn_estrela1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel_Botoes1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 108, Short.MAX_VALUE)
                .addComponent(jPanel_Botoes3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );

        jTabbedPane_Resposta.addTab("Respostas", jPanel_Respotas);

        getContentPane().add(jTabbedPane_Resposta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 490));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
        private void ler_Arquivo() {
		int returnVal = fc.showOpenDialog(this);
		if (returnVal == JFileChooser.APPROVE_OPTION) {
			File file = fc.getSelectedFile();
			System.out.println("Arquivo de score selecionado: " + file.getName() + ".");
			try {
				String arquivo = file.getAbsolutePath();
				FileReader arq = new FileReader(arquivo);
				BufferedReader lerArq = new BufferedReader(arq);
				String linha = lerArq.readLine();
				while (linha != null) {
					System.out.printf("%s\n", linha);
					linha = lerArq.readLine(); // lê da segunda até a última linha
				}

				arq.close();
			} catch (IOException e) {
				System.err.printf("Erro na abertura do arquivo: %s.\n",
					e.getMessage());
			}
		} else {
			System.out.println("Nenhum arquivo de score selecionado.");
		}
	}

	private void posicionar_indice(int p_valor) {
		this.max = lista_Resposta_Item.size();
		this.min = 0;
		this.indice += p_valor;
		this.jButton_Proximo.setEnabled(true);
		this.jButton_Anterior.setEnabled(true);
		this.jLabel_indice_pergunta.setText(null);
		this.jLabel_indice_posicao.setText(null);
		this.pn_estrela1.setEnabled(true);
		this.pn_estrela1.setVisible(true);
		if (p_valor < 0 ){
		    this.jButton_Confirma_Resposta.setEnabled(false);
		}
		if (this.max <= 0) {
			this.jButton_Proximo.setEnabled(false);
			this.jButton_Anterior.setEnabled(false);
			this.pn_estrela1.setVisible(false);
			this.pn_estrela1.setEnabled(false);
			this.jLabel_indice_posicao.setText("Nenhuma pergunta cadastrada..");
		} else {
			if (this.indice + 1 >= this.max) {
				this.indice = this.max - 1;
				this.jButton_Proximo.setEnabled(false);
				this.jButton_Confirma_Resposta.setEnabled(true);
			}
			if (this.indice < this.min) {
				this.indice = this.min;
				this.jButton_Anterior.setEnabled(false);
			}
			String s = "Pergunta " + String.valueOf(this.indice + 1) + " de " + this.max + ".";
			this.jLabel_indice_posicao.setText(s);
			Questionario_Resposta_Item qri = lista_Resposta_Item.get(indice);
			this.jLabel_indice_pergunta.setText(qri.getObservacao());
			this.pn_estrela1.setNumero_estrelas(qri.getValor());
		}

	}

	private void set_valor(){
		Questionario_Resposta_Item qri = lista_Resposta_Item.get(indice);
		qri.setValor(pn_estrela1.getNumero_estrelas());		
	
	}
        private void gravar(){
		set_valor();
		Questionario_Resposta qr = new Questionario_Resposta();
		qr.setQuestionario_resposta_id(dao.Questionario_Reposta_DAO.Questionario_Resposta_Id_Novo());
		qr.setQuestionario_id(Integer.valueOf(this.jTextField_questionario_id.getText()));
		qr.setNome(this.jTextField_nome.getText());
		qr.setE_mail(this.jTextField_email.getText());
	
		qr.setTotal_score(Integer.valueOf("0"+ this.jFormattedTextField_Score.getText()));
		qr.setTotal_tempo(Integer.valueOf("0"+ this.jFormattedTextField_Tempo.getText()));
			
		dao.Questionario_Reposta_DAO.inserir(qr);
		
		for (int i = 0; i < lista_Resposta_Item.size(); i++) {

		    Questionario_Resposta_Item qri = lista_Resposta_Item.get(i);
                    qri.setQuestionario_Resposta_id(qr.getQuestionario_resposta_id());
		    dao.Questionario_Resposta_Item_DAO.inserir(qri);
		}
		limpar(1);
	
	}
	private void confirmar() {
		
	                
                if (this.jTextField_questionario_id.getText().length() <= 0){
		   JOptionPane.showMessageDialog(this,"Questionário não informado.");					
		   return;
		}
		if (this.jTextField_nome.getText().length() <= 0 ) {
		  JOptionPane.showMessageDialog(this,"Nome não informado.");			
		  this.jTextField_nome.requestFocus();
		   return;
		}
		if (this.jTextField_email.getText().length() <= 0 ){
		   JOptionPane.showMessageDialog(this,"E-Mail não informado.");						
		   this.jTextField_email.requestFocus();
		   return;
		}
		Questionario_Resposta qr = new Questionario_Resposta();
		qr.setQuestionario_resposta_id(0);
		qr.setQuestionario_id(Integer.valueOf(this.jTextField_questionario_id.getText()));
		qr.setNome(this.jTextField_nome.getText());
		qr.setE_mail(this.jTextField_email.getText());
	        qr.setTotal_score(Integer.valueOf("0"+ this.jFormattedTextField_Score.getText()));
		qr.setTotal_tempo(Integer.valueOf("0"+ this.jFormattedTextField_Tempo.getText()));
	
		lista_Resposta_Item.clear();
		ArrayList<Questionario_Item> lista = new ArrayList();
		lista = dao.Questionario_Item_DAO.listar_Questionario_Resposta(qr.getQuestionario_id());
		System.out.println("Tamanho:" + lista.size());

		if (lista == null) {
			System.out.println("Nao existe");
		} else {
			for (Questionario_Item r : lista) {
				Questionario_Resposta_Item qri = new Questionario_Resposta_Item();		
				qri.setQuestionario_Resposta_id(qr.getQuestionario_resposta_id());
				qri.setQuestionario_item_id(r.getQuestionario_item_id());
				qri.setObservacao(r.getDescricao());
				qri.setQuestionario_item_id(r.getQuestionario_item_id());
				lista_Resposta_Item.add(qri);
			}
		}
		jTabbedPane_Resposta.setEnabledAt(0, false);
		jTabbedPane_Resposta.setEnabledAt(1, true);
		jTabbedPane_Resposta.setSelectedIndex(1);
		this.jButton_Confirma_Resposta.setEnabled(false);
		indice = 0;
		posicionar_indice(0);

	}

    private void limpar(int p_limpar_questionario) {
        if (p_limpar_questionario == 2) {
            this.jTextField_questionario_id.setText(null);
            this.jTextField_descricao.setText(null);
        }
        this.jTextField_nome.setText(null);
        this.jTextField_email.setText(null);
        this.jFormattedTextField_Score.setText(null);
        this.jFormattedTextField_Tempo.setText(null);
        this.jButton_Consultar.setEnabled(true);
        jTabbedPane_Resposta.setEnabledAt(0, true);
        jTabbedPane_Resposta.setEnabledAt(1, false);
        jTabbedPane_Resposta.setSelectedIndex(0);
        this.jTextField_nome.requestFocus();
	}

	private void lista_Questionario_Item(int p_id_questionario) {
		ArrayList<Questionario_Item> lista = new ArrayList();
		lista = dao.Questionario_Item_DAO.listar_Questionario_Resposta(p_id_questionario);
		if (lista == null) {
			System.out.println("Nao existe");
		} else {
			for (Questionario_Item r : lista) {
				System.out.println(r);
			}
		}
	}

	private void consultar() {
		if (this.jTextField_questionario_id.getText().length() <= 0) {
			Frm_Questionario_Lista frm_questionario_lista = new Frm_Questionario_Lista(this, true, 1);
			frm_questionario_lista.setVisible(true);
			if (frm_questionario_lista.questionario_id > 0) {
				this.jTextField_questionario_id.setText(frm_questionario_lista.questionario_id + "");
				jButton_ConsultarActionPerformed(null);
			}

		} else {
			Questionario q = new Questionario();
			q.setQuestionario_id(Integer.valueOf(this.jTextField_questionario_id.getText()));
			q = Questionario_DAO.consultar(q);
			if (q != null) {
				this.jTextField_questionario_id.setText(q.getQuestionario_id() + "");
				this.jTextField_descricao.setText(q.getDescricao());
				this.jButton_Consultar.setEnabled(false);
				this.jTextField_nome.requestFocus();
			} else {
				System.out.println("Registro inexistente.");
			}

		}
	}

        private void jButton_Sair1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair1ActionPerformed
		// TODO add your handling code here:
		this.dispose();
        }//GEN-LAST:event_jButton_Sair1ActionPerformed

        private void jButton_Cancelar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancelar1ActionPerformed
		// TODO add your handling code here:
		limpar(1);
        }//GEN-LAST:event_jButton_Cancelar1ActionPerformed

        private void jButton_Confirma_RespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Confirma_RespostaActionPerformed
		// TODO add your handling code here:
		// confirmar();
		gravar();
        }//GEN-LAST:event_jButton_Confirma_RespostaActionPerformed


        private void jButton_scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_scoreActionPerformed
		// TODO add youer handling code here:
		ler_Arquivo();
        }//GEN-LAST:event_jButton_scoreActionPerformed


        private void jButton_ConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConsultarActionPerformed
		consultar();
        }//GEN-LAST:event_jButton_ConsultarActionPerformed

        private void jTextField_descricaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_descricaoActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_jTextField_descricaoActionPerformed

        private void jTextField_questionario_idActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField_questionario_idActionPerformed
		// TODO add your handling code here:
        }//GEN-LAST:event_jTextField_questionario_idActionPerformed

        private void jButton_ConfirmaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ConfirmaActionPerformed
		// TODO add your handling code here:
		confirmar();
        }//GEN-LAST:event_jButton_ConfirmaActionPerformed

        private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        }//GEN-LAST:event_formWindowOpened

        private void jButton_Cancelar_RespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Cancelar_RespostaActionPerformed
		// TODO add your handling code here:
		limpar(1);
        }//GEN-LAST:event_jButton_Cancelar_RespostaActionPerformed

        private void jButton_Sair_RespostaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_Sair_RespostaActionPerformed
		// TODO add your handling code here:
		this.dispose();
        }//GEN-LAST:event_jButton_Sair_RespostaActionPerformed

        private void jButton_AnteriorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_AnteriorActionPerformed
		// TODO add your handling code here:
//		Questionario_Resposta_Item qri = lista_Resposta_Item.get(indice);
//		qri.setValor(pn_estrela1.getNumero_estrelas());
		set_valor();
		posicionar_indice(-1);
        }//GEN-LAST:event_jButton_AnteriorActionPerformed

        private void jButton_ProximoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProximoActionPerformed
//		Questionario_Resposta_Item qri = lista_Resposta_Item.get(indice);
//		qri.setValor(pn_estrela1.getNumero_estrelas());
		set_valor();
		posicionar_indice(1);                
        }//GEN-LAST:event_jButton_ProximoActionPerformed

        private void pn_estrela1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_pn_estrela1PropertyChange
		// TODO add your handling code here:

        }//GEN-LAST:event_pn_estrela1PropertyChange

        private void pn_estrela1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pn_estrela1MouseClicked
		// TODO add your handling code here:

        }//GEN-LAST:event_pn_estrela1MouseClicked

        private void jFormattedTextField_ScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_ScoreActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jFormattedTextField_ScoreActionPerformed

        private void jFormattedTextField_TempoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_TempoActionPerformed
                // TODO add your handling code here:
        }//GEN-LAST:event_jFormattedTextField_TempoActionPerformed

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		/* Set the Nimbus look and feel */
		//<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
		/* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
		 */
		try {
			for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
				if ("Nimbus".equals(info.getName())) {
					javax.swing.UIManager.setLookAndFeel(info.getClassName());
					break;
				}
			}
		} catch (ClassNotFoundException ex) {
			java.util.logging.Logger.getLogger(Frm_Resposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (InstantiationException ex) {
			java.util.logging.Logger.getLogger(Frm_Resposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (IllegalAccessException ex) {
			java.util.logging.Logger.getLogger(Frm_Resposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		} catch (javax.swing.UnsupportedLookAndFeelException ex) {
			java.util.logging.Logger.getLogger(Frm_Resposta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
		}
		//</editor-fold>

		/* Create and display the form */
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				//new Frm_Resposta().setVisible(true);
				Frm_Resposta f = new Frm_Resposta();
				f.setVisible(true);
				f.setLocationRelativeTo(null);
			}
		});
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Anterior;
    private javax.swing.JButton jButton_Cancelar1;
    private javax.swing.JButton jButton_Cancelar_Resposta;
    private javax.swing.JButton jButton_Confirma;
    private javax.swing.JButton jButton_Confirma_Resposta;
    private javax.swing.JButton jButton_Consultar;
    private javax.swing.JButton jButton_Proximo;
    private javax.swing.JButton jButton_Sair1;
    private javax.swing.JButton jButton_Sair_Resposta;
    private javax.swing.JButton jButton_score;
    private javax.swing.JFormattedTextField jFormattedTextField_Score;
    private javax.swing.JFormattedTextField jFormattedTextField_Tempo;
    private javax.swing.JLabel jLabel_descricao;
    private javax.swing.JLabel jLabel_email;
    private javax.swing.JLabel jLabel_indice_pergunta;
    private javax.swing.JLabel jLabel_indice_posicao;
    private javax.swing.JLabel jLabel_nome;
    private javax.swing.JLabel jLabel_questionario_id;
    private javax.swing.JLabel jLabel_score;
    private javax.swing.JLabel jLabel_tempo;
    private javax.swing.JPanel jPanel_Botoes1;
    private javax.swing.JPanel jPanel_Botoes2;
    private javax.swing.JPanel jPanel_Botoes3;
    private javax.swing.JPanel jPanel_Questionario;
    private javax.swing.JPanel jPanel_Respotas;
    private javax.swing.JTabbedPane jTabbedPane_Resposta;
    private javax.swing.JTextField jTextField_descricao;
    private javax.swing.JTextField jTextField_email;
    private javax.swing.JTextField jTextField_nome;
    private javax.swing.JTextField jTextField_questionario_id;
    private componente.pn_estrela pn_estrela1;
    // End of variables declaration//GEN-END:variables
}
